### ISSUE TITLE
Developer guide user stories formatting

### ISSUE THREAD

**Issue by JoelChanZhiYang** [AY2122S1-CS2103T-T17-4/tp#55]
The following user stories do not fit the format of user stories. 
1. > wants to record the time and place of my appointments
2. > all the contacts in my address book to be arranged alphabetically by their First Name
3. > be able to easily calculate the commissions I get from my clients
4. > be able to delete people from my contact list
5. > be able to use programs on Windows and Mac
6. > be able to install the application
7. > be able to filter out the contacts in my address book based on address
8. > be able to back up my client data
9. > be able to see the labels attached to each client easily

**Comment by xianlinc** [comment]
You can check out the format for User Stories here : [https://nus-cs2103-ay2122s1.github.io/website/se-book-adapted/chapters/specifyingRequirements.html#user-stories](link)
